In [1]:
import numpy as np

In [6]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        return output
    
values = np.random.randint(1, 10, size = 5)
print(values)
    
compute_reciprocals(values)

[2 5 1 6 8]


array([5.00000000e-001, 1.00000000e+000, 2.41322069e-038, 9.40712658e-023,
       1.28625394e+248])

In [7]:
big_array = np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

15.8 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%timeit 1 / big_array

3.12 ms ± 60 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
np.random.seed(1)
arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))
print(arr1, arr2)

arr1= arr1 - 2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]


In [13]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [15]:
theta = np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [17]:
x = np.arange(1,5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [18]:
x = np.arange(1, 15)
print(x)

accum = np.multiply.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [20]:
np.random.seed(2)
arr = np.random.rand(1000000) 

print(arr)
print('sum::=', np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.78483191 0.00778062 0.42442656]
sum::= 499468.5166853333
139 ms ± 3.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%timeit np.sum(arr)

1.08 ms ± 17.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
print("max=", np.max(arr))
print("min=", np.min(arr))
print("mean=", np.mean(arr))
print("median=", np.median(arr))
print("percentile=", np.percentile(arr, 90))
print(np.any(arr>1))
print(np.all(arr>0))

max= 0.9999976661165695
min= 9.475783189216713e-07
mean= 0.49946851668533326
median= 0.49948650836352526
percentile= 0.9004310892470595
False
True


In [24]:
np.random.seed(5)

arr= np.random.randint(10, size=(3, 4))
print(arr)

print(np.sum(arr, axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[15 28  8]
